[project]
name = "algolabra"
version = "0.1.0"
description = ""
authors = [
    {name = "TommiAL",email = "kohonen.tommi21@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "pylint (>=4.0.8,<5.0.0)",
    "soundfile (>=0.14.0,<0.15.0)",
    "matplotlib (>=3.11.2,<4.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
package-mode = false

[dependency-groups]
dev = [
    "coverage (>=7.16.0,<8.0.0)",
    "pytest (>=9.1.1,<10.0.0)"
]
